name: core
description: 공통 핵심 기능을 제공하는 패키지

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management - melos에서 버전 관리
  flutter_riverpod:
  riverpod_annotation:
  
  # Dependency Injection - melos에서 버전 관리
  get_it:
  injectable:
  
  # Networking - melos에서 버전 관리
  dio:
  retrofit:
  
  # Database - melos에서 버전 관리
  hive:
  hive_flutter:
  
  # JSON Serialization - melos에서 버전 관리
  json_annotation:
  
  # Data Modeling - melos에서 버전 관리
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation - melos에서 버전 관리
  build_runner:
  injectable_generator:
  json_serializable:
  retrofit_generator:
  hive_generator:
  riverpod_generator:
  freezed:
  
  # Testing - melos에서 버전 관리
  mocktail: