name: core
description: 공통 핵심 기능을 제공하는 패키지

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  dio:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  get_it:
  hive_flutter:
  injectable:
  json_annotation:
  retrofit:
  riverpod_annotation:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator:
  injectable_generator:
  json_serializable:
  mocktail:
  retrofit_generator:
  riverpod_generator:
